package main

import (
	"cake/proto/pb"
	"fmt"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"strings"
)

const (
	globalFileName = "cmdid_global_map.pb.go"
	headerComment  = "// Code generated by gen-proto-routers. DO NOT EDIT."
	globalPkg      = "pb"
)

func main() {
	protogen.Options{}.Run(func(plugin *protogen.Plugin) error {
		var allMsgs []*protogen.Message
		for _, file := range plugin.Files {
			if !file.Generate {
				continue
			}
			allMsgs = append(allMsgs, file.Messages...)
		}

		if len(allMsgs) == 0 {
			return nil
		}

		g := plugin.NewGeneratedFile(globalFileName, globalPkg)

		g.P(headerComment)
		g.P()
		g.P("package ", globalPkg)
		g.P()

		g.P("import (")
		g.P(`	"google.golang.org/protobuf/proto"`)
		g.P(`	"reflect"`)
		g.P(")")
		g.P()

		genAllMap(g, allMsgs)
		genHelperFunc(g)

		return nil
	})
}

func genAllMap(g *protogen.GeneratedFile, msgs []*protogen.Message) {
	// 1. 全量总表：所有上行C2S + 下行S2C 全部放入
	g.P("// MsgAllTypeToCmd 全量消息映射：所有C2S、S2C消息类型 -> 协议号")
	g.P(`var MsgAllTypeToCmd = map[reflect.Type]uint32{`)
	g.P(`	//goland:noinspection GoUnusedGlobalVariable`)
	for _, msg := range msgs {
		cmdID := getCmdID(msg)
		if cmdID == 0 {
			continue
		}
		msgName := msg.GoIdent.GoName
		g.P(fmt.Sprintf("	reflect.TypeOf((*%s)(nil)): %d,", msgName, cmdID))
	}
	g.P("}")
	g.P()

	// 2. C2S上行表：只放非S2C结尾，和你原来格式完全一致
	g.P("// C2STypeToCmd 客户端上行请求：消息类型映射协议号")
	g.P(`var C2STypeToCmd = map[reflect.Type]uint32{`)
	g.P(`	//goland:noinspection GoUnusedGlobalVariable`)
	for _, msg := range msgs {
		cmdID := getCmdID(msg)
		if cmdID == 0 {
			continue
		}
		msgName := msg.GoIdent.GoName
		if !strings.HasSuffix(msgName, "S2C") {
			g.P(fmt.Sprintf("	reflect.TypeOf((*%s)(nil)): %d,", msgName, cmdID))
		}
	}
	g.P("}")
	g.P()

	// 3. S2C下行表：只放S2C结尾，协议号->类型
	g.P("// CmdToS2C 服务端下行响应：协议号映射消息类型")
	g.P(`var CmdToS2C = map[uint32]reflect.Type{`)
	g.P(`	//goland:noinspection GoUnusedGlobalVariable`)
	for _, msg := range msgs {
		cmdID := getCmdID(msg)
		if cmdID == 0 {
			continue
		}
		msgName := msg.GoIdent.GoName
		if strings.HasSuffix(msgName, "S2C") {
			g.P(fmt.Sprintf("	%d: reflect.TypeOf((*%s)(nil)),", cmdID, msgName))
		}
	}
	g.P("}")
	g.P()
}

func genHelperFunc(g *protogen.GeneratedFile) {
	// 1. 全局通用：任意消息（C2S/S2C）获取协议号
	g.P("// GetAllCmdByMsg 通用方法：传入任意C2S/S2C消息，获取协议号")
	g.P("func GetAllCmdByMsg(msg proto.Message) (uint32, reflect.Type, bool) {")
	g.P("	if msg == nil {")
	g.P("		return 0, nil, false")
	g.P("	}")
	g.P("	t := reflect.TypeOf(msg)")
	g.P("	cmdID, ok := MsgAllTypeToCmd[t]")
	g.P("	return cmdID, t, ok")
	g.P("}")
	g.P()

	// 2. 仅C2S上行获取协议号（原有路由绑定用）
	g.P("// GetC2SCmdByMsg 仅C2S请求获取协议号")
	g.P("func GetC2SCmdByMsg(msg proto.Message) (uint32, reflect.Type, bool) {")
	g.P("	if msg == nil {")
	g.P("		return 0, nil, false")
	g.P("	}")
	g.P("	t := reflect.TypeOf(msg)")
	g.P("	cmdID, ok := C2STypeToCmd[t]")
	g.P("	return cmdID, t, ok")
	g.P("}")
	g.P()

	// 3. 根据协议号获取S2C下行类型（发送日志解析用）
	g.P("// GetS2CTypeByCmd 根据协议号获取S2C响应消息反射类型")
	g.P("func GetS2CTypeByCmd(cmd uint32) (reflect.Type, bool) {")
	g.P("	typ, ok := CmdToS2C[cmd]")
	g.P("	return typ, ok")
	g.P("}")
	g.P()
}

func getCmdID(msg *protogen.Message) int32 {
	opts := msg.Desc.Options()
	if !proto.HasExtension(opts, pb.E_CmdId) {
		return 0
	}
	val := proto.GetExtension(opts, pb.E_CmdId)
	if v, ok := val.(int32); ok {
		return v
	}
	return 0
}
