// Code generated by gen-proto-routers. DO NOT EDIT.

package pb

import (
	"google.golang.org/protobuf/proto"
	"reflect"
)

// MsgAllTypeToCmd 全量消息映射：所有C2S、S2C消息类型 -> 协议号
var MsgAllTypeToCmd = map[reflect.Type]uint32{
	//goland:noinspection GoUnusedGlobalVariable
	reflect.TypeOf((*HeartbeatC2S)(nil)):    1000,
	reflect.TypeOf((*HeartbeatS2C)(nil)):    1000,
	reflect.TypeOf((*AccountAuthC2S)(nil)):  1001,
	reflect.TypeOf((*AccountAuthS2C)(nil)):  1001,
	reflect.TypeOf((*SelectRolesC2S)(nil)):  1002,
	reflect.TypeOf((*SelectRolesS2C)(nil)):  1002,
	reflect.TypeOf((*CreateRoleC2S)(nil)):   1003,
	reflect.TypeOf((*CreateRoleS2C)(nil)):   1003,
	reflect.TypeOf((*LoginRoleC2S)(nil)):    1004,
	reflect.TypeOf((*LoginRoleS2C)(nil)):    1004,
	reflect.TypeOf((*EnterSceneC2S)(nil)):   2000,
	reflect.TypeOf((*EnterSceneS2C)(nil)):   2000,
	reflect.TypeOf((*MovePosC2S)(nil)):      2001,
	reflect.TypeOf((*MovePosS2C)(nil)):      2001,
	reflect.TypeOf((*RoleViewListS2C)(nil)): 2002,
	reflect.TypeOf((*RoleViewDelS2C)(nil)):  2003,
	reflect.TypeOf((*TestC2S)(nil)):         10000,
	reflect.TypeOf((*TestS2C)(nil)):         10000,
}

// C2STypeToCmd 客户端上行请求：消息类型映射协议号
var C2STypeToCmd = map[reflect.Type]uint32{
	//goland:noinspection GoUnusedGlobalVariable
	reflect.TypeOf((*HeartbeatC2S)(nil)):   1000,
	reflect.TypeOf((*AccountAuthC2S)(nil)): 1001,
	reflect.TypeOf((*SelectRolesC2S)(nil)): 1002,
	reflect.TypeOf((*CreateRoleC2S)(nil)):  1003,
	reflect.TypeOf((*LoginRoleC2S)(nil)):   1004,
	reflect.TypeOf((*EnterSceneC2S)(nil)):  2000,
	reflect.TypeOf((*MovePosC2S)(nil)):     2001,
	reflect.TypeOf((*TestC2S)(nil)):        10000,
}

// CmdToS2C 服务端下行响应：协议号映射消息类型
var CmdToS2C = map[uint32]reflect.Type{
	//goland:noinspection GoUnusedGlobalVariable
	1000:  reflect.TypeOf((*HeartbeatS2C)(nil)),
	1001:  reflect.TypeOf((*AccountAuthS2C)(nil)),
	1002:  reflect.TypeOf((*SelectRolesS2C)(nil)),
	1003:  reflect.TypeOf((*CreateRoleS2C)(nil)),
	1004:  reflect.TypeOf((*LoginRoleS2C)(nil)),
	2000:  reflect.TypeOf((*EnterSceneS2C)(nil)),
	2001:  reflect.TypeOf((*MovePosS2C)(nil)),
	2002:  reflect.TypeOf((*RoleViewListS2C)(nil)),
	2003:  reflect.TypeOf((*RoleViewDelS2C)(nil)),
	10000: reflect.TypeOf((*TestS2C)(nil)),
}

// GetAllCmdByMsg 通用方法：传入任意C2S/S2C消息，获取协议号
func GetAllCmdByMsg(msg proto.Message) (uint32, reflect.Type, bool) {
	if msg == nil {
		return 0, nil, false
	}
	t := reflect.TypeOf(msg)
	cmdID, ok := MsgAllTypeToCmd[t]
	return cmdID, t, ok
}

// GetC2SCmdByMsg 仅C2S请求获取协议号
func GetC2SCmdByMsg(msg proto.Message) (uint32, reflect.Type, bool) {
	if msg == nil {
		return 0, nil, false
	}
	t := reflect.TypeOf(msg)
	cmdID, ok := C2STypeToCmd[t]
	return cmdID, t, ok
}

// GetS2CTypeByCmd 根据协议号获取S2C响应消息反射类型
func GetS2CTypeByCmd(cmd uint32) (reflect.Type, bool) {
	typ, ok := CmdToS2C[cmd]
	return typ, ok
}
