// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       uint32                 `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"` //0为成功
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notice) Reset() {
	*x = Notice{}
	mi := &file_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notice) ProtoMessage() {}

func (x *Notice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notice.ProtoReflect.Descriptor instead.
func (*Notice) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *Notice) GetErrCode() uint32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *Notice) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type Pos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             uint32                 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pos) Reset() {
	*x = Pos{}
	mi := &file_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pos) ProtoMessage() {}

func (x *Pos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pos.ProtoReflect.Descriptor instead.
func (*Pos) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *Pos) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Pos) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SceneRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        uint64                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`       //角色id
	ServerId      uint32                 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` //服务器id
	PlatId        uint32                 `protobuf:"varint,3,opt,name=plat_id,json=platId,proto3" json:"plat_id,omitempty"`       //平台id
	RoleName      string                 `protobuf:"bytes,4,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`  //平台id
	Pos           *Pos                   `protobuf:"bytes,5,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneRole) Reset() {
	*x = SceneRole{}
	mi := &file_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneRole) ProtoMessage() {}

func (x *SceneRole) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneRole.ProtoReflect.Descriptor instead.
func (*SceneRole) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *SceneRole) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *SceneRole) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *SceneRole) GetPlatId() uint32 {
	if x != nil {
		return x.PlatId
	}
	return 0
}

func (x *SceneRole) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *SceneRole) GetPos() *Pos {
	if x != nil {
		return x.Pos
	}
	return nil
}

var file_proto_common_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         50001,
		Name:          "common.cmd_id",
		Tag:           "varint,50001,opt,name=cmd_id",
		Filename:      "proto/common.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional int32 cmd_id = 50001;
	E_CmdId = &file_proto_common_proto_extTypes[0]
)

var File_proto_common_proto protoreflect.FileDescriptor

const file_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x12proto/common.proto\x12\x06common\x1a google/protobuf/descriptor.proto\"<\n" +
	"\x06notice\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\rR\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\"!\n" +
	"\x03pos\x12\f\n" +
	"\x01x\x18\x01 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\rR\x01y\"\x97\x01\n" +
	"\n" +
	"scene_role\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x04R\x06roleId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\rR\bserverId\x12\x17\n" +
	"\aplat_id\x18\x03 \x01(\rR\x06platId\x12\x1b\n" +
	"\trole_name\x18\x04 \x01(\tR\broleName\x12\x1d\n" +
	"\x03pos\x18\x05 \x01(\v2\v.common.posR\x03pos:8\n" +
	"\x06cmd_id\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x01(\x05R\x05cmdIdB\rZ\vproto/pb;pbb\x06proto3"

var (
	file_proto_common_proto_rawDescOnce sync.Once
	file_proto_common_proto_rawDescData []byte
)

func file_proto_common_proto_rawDescGZIP() []byte {
	file_proto_common_proto_rawDescOnce.Do(func() {
		file_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)))
	})
	return file_proto_common_proto_rawDescData
}

var file_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_common_proto_goTypes = []any{
	(*Notice)(nil),                      // 0: common.notice
	(*Pos)(nil),                         // 1: common.pos
	(*SceneRole)(nil),                   // 2: common.scene_role
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
}
var file_proto_common_proto_depIdxs = []int32{
	1, // 0: common.scene_role.pos:type_name -> common.pos
	3, // 1: common.cmd_id:extendee -> google.protobuf.MessageOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_common_proto_init() }
func file_proto_common_proto_init() {
	if File_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_proto_goTypes,
		DependencyIndexes: file_proto_common_proto_depIdxs,
		MessageInfos:      file_proto_common_proto_msgTypes,
		ExtensionInfos:    file_proto_common_proto_extTypes,
	}.Build()
	File_proto_common_proto = out.File
	file_proto_common_proto_goTypes = nil
	file_proto_common_proto_depIdxs = nil
}
