// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/login.proto

// 包名

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//心跳包
//code=1000
type HeartbeatC2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTime    int64                  `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"` //客户端ping时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatC2S) Reset() {
	*x = HeartbeatC2S{}
	mi := &file_proto_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatC2S) ProtoMessage() {}

func (x *HeartbeatC2S) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatC2S.ProtoReflect.Descriptor instead.
func (*HeartbeatC2S) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatC2S) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

type HeartbeatS2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTime    int64                  `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"` //客户端ping时间
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` //服务器时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatS2C) Reset() {
	*x = HeartbeatS2C{}
	mi := &file_proto_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatS2C) ProtoMessage() {}

func (x *HeartbeatS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatS2C.ProtoReflect.Descriptor instead.
func (*HeartbeatS2C) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatS2C) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

func (x *HeartbeatS2C) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// 尝试登录系统
//code=1001
type AccountAuthC2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`                                  // 账号
	ServerId      uint32                 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`               // 服务器id
	PlatId        uint32                 `protobuf:"varint,3,opt,name=plat_id,json=platId,proto3" json:"plat_id,omitempty"`                     // 平台ID
	Ticket        string                 `protobuf:"bytes,4,opt,name=ticket,proto3" json:"ticket,omitempty"`                                    // 通过sdk获取的验证信息
	ClientVersion string                 `protobuf:"bytes,5,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"` //客户端版本
	ChannelId     uint32                 `protobuf:"varint,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`            // 渠道ID（分包、联运渠道）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountAuthC2S) Reset() {
	*x = AccountAuthC2S{}
	mi := &file_proto_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountAuthC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountAuthC2S) ProtoMessage() {}

func (x *AccountAuthC2S) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountAuthC2S.ProtoReflect.Descriptor instead.
func (*AccountAuthC2S) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{2}
}

func (x *AccountAuthC2S) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountAuthC2S) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *AccountAuthC2S) GetPlatId() uint32 {
	if x != nil {
		return x.PlatId
	}
	return 0
}

func (x *AccountAuthC2S) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *AccountAuthC2S) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *AccountAuthC2S) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

type AccountAuthS2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommonNotice  *Notice                `protobuf:"bytes,1,opt,name=common_notice,json=commonNotice,proto3" json:"common_notice,omitempty"`
	IsAuth        bool                   `protobuf:"varint,2,opt,name=is_auth,json=isAuth,proto3" json:"is_auth,omitempty"` //是否认证通过
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountAuthS2C) Reset() {
	*x = AccountAuthS2C{}
	mi := &file_proto_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountAuthS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountAuthS2C) ProtoMessage() {}

func (x *AccountAuthS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountAuthS2C.ProtoReflect.Descriptor instead.
func (*AccountAuthS2C) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{3}
}

func (x *AccountAuthS2C) GetCommonNotice() *Notice {
	if x != nil {
		return x.CommonNotice
	}
	return nil
}

func (x *AccountAuthS2C) GetIsAuth() bool {
	if x != nil {
		return x.IsAuth
	}
	return false
}

//code=1002
type SelectRolesC2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`                    // 账号
	PlatId        uint32                 `protobuf:"varint,2,opt,name=plat_id,json=platId,proto3" json:"plat_id,omitempty"`       // 首选：平台ID
	ServerId      uint32                 `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` // 服务器id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectRolesC2S) Reset() {
	*x = SelectRolesC2S{}
	mi := &file_proto_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRolesC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRolesC2S) ProtoMessage() {}

func (x *SelectRolesC2S) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRolesC2S.ProtoReflect.Descriptor instead.
func (*SelectRolesC2S) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{4}
}

func (x *SelectRolesC2S) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SelectRolesC2S) GetPlatId() uint32 {
	if x != nil {
		return x.PlatId
	}
	return 0
}

func (x *SelectRolesC2S) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type SelectRolesS2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommonNotice  *Notice                `protobuf:"bytes,1,opt,name=common_notice,json=commonNotice,proto3" json:"common_notice,omitempty"`
	RoleList      []*RoleInfo            `protobuf:"bytes,2,rep,name=role_list,json=roleList,proto3" json:"role_list,omitempty"` // 角色列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectRolesS2C) Reset() {
	*x = SelectRolesS2C{}
	mi := &file_proto_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRolesS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRolesS2C) ProtoMessage() {}

func (x *SelectRolesS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRolesS2C.ProtoReflect.Descriptor instead.
func (*SelectRolesS2C) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{5}
}

func (x *SelectRolesS2C) GetCommonNotice() *Notice {
	if x != nil {
		return x.CommonNotice
	}
	return nil
}

func (x *SelectRolesS2C) GetRoleList() []*RoleInfo {
	if x != nil {
		return x.RoleList
	}
	return nil
}

//code=1003
type CreateRoleC2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                          //角色名
	ServerId      uint32                 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` //服务器id
	PlatId        uint32                 `protobuf:"varint,3,opt,name=plat_id,json=platId,proto3" json:"plat_id,omitempty"`       //平台id
	Gender        uint32                 `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`                     //性别
	Career        uint32                 `protobuf:"varint,5,opt,name=career,proto3" json:"career,omitempty"`                     //职业
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleC2S) Reset() {
	*x = CreateRoleC2S{}
	mi := &file_proto_login_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleC2S) ProtoMessage() {}

func (x *CreateRoleC2S) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleC2S.ProtoReflect.Descriptor instead.
func (*CreateRoleC2S) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRoleC2S) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleC2S) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *CreateRoleC2S) GetPlatId() uint32 {
	if x != nil {
		return x.PlatId
	}
	return 0
}

func (x *CreateRoleC2S) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *CreateRoleC2S) GetCareer() uint32 {
	if x != nil {
		return x.Career
	}
	return 0
}

type CreateRoleS2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommonNotice  *Notice                `protobuf:"bytes,1,opt,name=common_notice,json=commonNotice,proto3" json:"common_notice,omitempty"`
	RoleId        uint64                 `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`       //角色id
	ServerId      uint32                 `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` //服务器id
	PlatId        uint32                 `protobuf:"varint,4,opt,name=plat_id,json=platId,proto3" json:"plat_id,omitempty"`       //平台i
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`                          //角色名
	Gender        uint32                 `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`                     //性别
	Career        uint32                 `protobuf:"varint,7,opt,name=career,proto3" json:"career,omitempty"`                     //职业
	Lv            uint32                 `protobuf:"varint,8,opt,name=lv,proto3" json:"lv,omitempty"`                             //等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleS2C) Reset() {
	*x = CreateRoleS2C{}
	mi := &file_proto_login_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleS2C) ProtoMessage() {}

func (x *CreateRoleS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleS2C.ProtoReflect.Descriptor instead.
func (*CreateRoleS2C) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRoleS2C) GetCommonNotice() *Notice {
	if x != nil {
		return x.CommonNotice
	}
	return nil
}

func (x *CreateRoleS2C) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *CreateRoleS2C) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *CreateRoleS2C) GetPlatId() uint32 {
	if x != nil {
		return x.PlatId
	}
	return 0
}

func (x *CreateRoleS2C) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleS2C) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *CreateRoleS2C) GetCareer() uint32 {
	if x != nil {
		return x.Career
	}
	return 0
}

func (x *CreateRoleS2C) GetLv() uint32 {
	if x != nil {
		return x.Lv
	}
	return 0
}

//code=1004
type LoginRoleC2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        uint64                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` //角色名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRoleC2S) Reset() {
	*x = LoginRoleC2S{}
	mi := &file_proto_login_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRoleC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRoleC2S) ProtoMessage() {}

func (x *LoginRoleC2S) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRoleC2S.ProtoReflect.Descriptor instead.
func (*LoginRoleC2S) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{8}
}

func (x *LoginRoleC2S) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type LoginRoleS2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommonNotice  *Notice                `protobuf:"bytes,1,opt,name=common_notice,json=commonNotice,proto3" json:"common_notice,omitempty"`
	RoleId        uint64                 `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`       //角色id
	ServerId      uint32                 `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` //服务器id
	PlatId        uint32                 `protobuf:"varint,4,opt,name=plat_id,json=platId,proto3" json:"plat_id,omitempty"`       //平台id
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`                          //角色名
	Gender        uint32                 `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`                     //性别
	Career        uint32                 `protobuf:"varint,7,opt,name=career,proto3" json:"career,omitempty"`                     //职业
	Lv            uint32                 `protobuf:"varint,8,opt,name=lv,proto3" json:"lv,omitempty"`                             //等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRoleS2C) Reset() {
	*x = LoginRoleS2C{}
	mi := &file_proto_login_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRoleS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRoleS2C) ProtoMessage() {}

func (x *LoginRoleS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRoleS2C.ProtoReflect.Descriptor instead.
func (*LoginRoleS2C) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{9}
}

func (x *LoginRoleS2C) GetCommonNotice() *Notice {
	if x != nil {
		return x.CommonNotice
	}
	return nil
}

func (x *LoginRoleS2C) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *LoginRoleS2C) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *LoginRoleS2C) GetPlatId() uint32 {
	if x != nil {
		return x.PlatId
	}
	return 0
}

func (x *LoginRoleS2C) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginRoleS2C) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *LoginRoleS2C) GetCareer() uint32 {
	if x != nil {
		return x.Career
	}
	return 0
}

func (x *LoginRoleS2C) GetLv() uint32 {
	if x != nil {
		return x.Lv
	}
	return 0
}

//============================================================
type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        uint64                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`       // 角色id
	ServerId      uint32                 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` // 角色ID
	PlatId        uint32                 `protobuf:"varint,3,opt,name=plat_id,json=platId,proto3" json:"plat_id,omitempty"`       // 平台id
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                          // 角色名
	Gender        uint32                 `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`                     // 性别
	Lv            uint32                 `protobuf:"varint,6,opt,name=lv,proto3" json:"lv,omitempty"`                             // 等级
	Career        uint32                 `protobuf:"varint,7,opt,name=career,proto3" json:"career,omitempty"`                     // 职业
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_proto_login_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{10}
}

func (x *RoleInfo) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RoleInfo) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *RoleInfo) GetPlatId() uint32 {
	if x != nil {
		return x.PlatId
	}
	return 0
}

func (x *RoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *RoleInfo) GetLv() uint32 {
	if x != nil {
		return x.Lv
	}
	return 0
}

func (x *RoleInfo) GetCareer() uint32 {
	if x != nil {
		return x.Career
	}
	return 0
}

var File_proto_login_proto protoreflect.FileDescriptor

const file_proto_login_proto_rawDesc = "" +
	"\n" +
	"\x11proto/login.proto\x12\x05login\x1a\x12proto/common.proto\"6\n" +
	"\fHeartbeatC2S\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime:\x05\x88\xb5\x18\xe8\a\"W\n" +
	"\fHeartbeatS2C\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime:\x05\x88\xb5\x18\xe8\a\"\xc5\x01\n" +
	"\x0eAccountAuthC2S\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\rR\bserverId\x12\x17\n" +
	"\aplat_id\x18\x03 \x01(\rR\x06platId\x12\x16\n" +
	"\x06ticket\x18\x04 \x01(\tR\x06ticket\x12%\n" +
	"\x0eclient_version\x18\x05 \x01(\tR\rclientVersion\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x06 \x01(\rR\tchannelId:\x05\x88\xb5\x18\xe9\a\"e\n" +
	"\x0eAccountAuthS2C\x123\n" +
	"\rcommon_notice\x18\x01 \x01(\v2\x0e.common.noticeR\fcommonNotice\x12\x17\n" +
	"\ais_auth\x18\x02 \x01(\bR\x06isAuth:\x05\x88\xb5\x18\xe9\a\"g\n" +
	"\x0eSelectRolesC2S\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x17\n" +
	"\aplat_id\x18\x02 \x01(\rR\x06platId\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\rR\bserverId:\x05\x88\xb5\x18\xea\a\"z\n" +
	"\x0eSelectRolesS2C\x123\n" +
	"\rcommon_notice\x18\x01 \x01(\v2\x0e.common.noticeR\fcommonNotice\x12,\n" +
	"\trole_list\x18\x02 \x03(\v2\x0f.login.RoleInfoR\broleList:\x05\x88\xb5\x18\xea\a\"\x90\x01\n" +
	"\rCreateRoleC2S\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\rR\bserverId\x12\x17\n" +
	"\aplat_id\x18\x03 \x01(\rR\x06platId\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\rR\x06gender\x12\x16\n" +
	"\x06career\x18\x05 \x01(\rR\x06career:\x05\x88\xb5\x18\xeb\a\"\xee\x01\n" +
	"\rCreateRoleS2C\x123\n" +
	"\rcommon_notice\x18\x01 \x01(\v2\x0e.common.noticeR\fcommonNotice\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x04R\x06roleId\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\rR\bserverId\x12\x17\n" +
	"\aplat_id\x18\x04 \x01(\rR\x06platId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\rR\x06gender\x12\x16\n" +
	"\x06career\x18\a \x01(\rR\x06career\x12\x0e\n" +
	"\x02lv\x18\b \x01(\rR\x02lv:\x05\x88\xb5\x18\xeb\a\".\n" +
	"\fLoginRoleC2S\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x04R\x06roleId:\x05\x88\xb5\x18\xec\a\"\xed\x01\n" +
	"\fLoginRoleS2C\x123\n" +
	"\rcommon_notice\x18\x01 \x01(\v2\x0e.common.noticeR\fcommonNotice\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x04R\x06roleId\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\rR\bserverId\x12\x17\n" +
	"\aplat_id\x18\x04 \x01(\rR\x06platId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\rR\x06gender\x12\x16\n" +
	"\x06career\x18\a \x01(\rR\x06career\x12\x0e\n" +
	"\x02lv\x18\b \x01(\rR\x02lv:\x05\x88\xb5\x18\xec\a\"\xad\x01\n" +
	"\bRoleInfo\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x04R\x06roleId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\rR\bserverId\x12\x17\n" +
	"\aplat_id\x18\x03 \x01(\rR\x06platId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\rR\x06gender\x12\x0e\n" +
	"\x02lv\x18\x06 \x01(\rR\x02lv\x12\x16\n" +
	"\x06career\x18\a \x01(\rR\x06careerB\rZ\vproto/pb;pbP\x00b\x06proto3"

var (
	file_proto_login_proto_rawDescOnce sync.Once
	file_proto_login_proto_rawDescData []byte
)

func file_proto_login_proto_rawDescGZIP() []byte {
	file_proto_login_proto_rawDescOnce.Do(func() {
		file_proto_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_login_proto_rawDesc), len(file_proto_login_proto_rawDesc)))
	})
	return file_proto_login_proto_rawDescData
}

var file_proto_login_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_login_proto_goTypes = []any{
	(*HeartbeatC2S)(nil),   // 0: login.HeartbeatC2S
	(*HeartbeatS2C)(nil),   // 1: login.HeartbeatS2C
	(*AccountAuthC2S)(nil), // 2: login.AccountAuthC2S
	(*AccountAuthS2C)(nil), // 3: login.AccountAuthS2C
	(*SelectRolesC2S)(nil), // 4: login.SelectRolesC2S
	(*SelectRolesS2C)(nil), // 5: login.SelectRolesS2C
	(*CreateRoleC2S)(nil),  // 6: login.CreateRoleC2S
	(*CreateRoleS2C)(nil),  // 7: login.CreateRoleS2C
	(*LoginRoleC2S)(nil),   // 8: login.LoginRoleC2S
	(*LoginRoleS2C)(nil),   // 9: login.LoginRoleS2C
	(*RoleInfo)(nil),       // 10: login.RoleInfo
	(*Notice)(nil),         // 11: common.notice
}
var file_proto_login_proto_depIdxs = []int32{
	11, // 0: login.AccountAuthS2C.common_notice:type_name -> common.notice
	11, // 1: login.SelectRolesS2C.common_notice:type_name -> common.notice
	10, // 2: login.SelectRolesS2C.role_list:type_name -> login.RoleInfo
	11, // 3: login.CreateRoleS2C.common_notice:type_name -> common.notice
	11, // 4: login.LoginRoleS2C.common_notice:type_name -> common.notice
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_login_proto_init() }
func file_proto_login_proto_init() {
	if File_proto_login_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_login_proto_rawDesc), len(file_proto_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_login_proto_goTypes,
		DependencyIndexes: file_proto_login_proto_depIdxs,
		MessageInfos:      file_proto_login_proto_msgTypes,
	}.Build()
	File_proto_login_proto = out.File
	file_proto_login_proto_goTypes = nil
	file_proto_login_proto_depIdxs = nil
}
