// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: proto/scene.proto

// 包名

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//进入场景 优先scene_id，如果scene_id为0 转大场景map_id
type EnterSceneC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneId uint32 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"` //场景id
	MapId   uint32 `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`       //地图id
}

func (x *EnterSceneC2S) Reset() {
	*x = EnterSceneC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterSceneC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSceneC2S) ProtoMessage() {}

func (x *EnterSceneC2S) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSceneC2S.ProtoReflect.Descriptor instead.
func (*EnterSceneC2S) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{0}
}

func (x *EnterSceneC2S) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *EnterSceneC2S) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

type EnterSceneS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonNotice *Notice `protobuf:"bytes,1,opt,name=common_notice,json=commonNotice,proto3" json:"common_notice,omitempty"`
	SceneId      uint32  `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"` //场景id
	MapId        uint32  `protobuf:"varint,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`       //地图id
	Pos          *Pos    `protobuf:"bytes,4,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *EnterSceneS2C) Reset() {
	*x = EnterSceneS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterSceneS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSceneS2C) ProtoMessage() {}

func (x *EnterSceneS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSceneS2C.ProtoReflect.Descriptor instead.
func (*EnterSceneS2C) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{1}
}

func (x *EnterSceneS2C) GetCommonNotice() *Notice {
	if x != nil {
		return x.CommonNotice
	}
	return nil
}

func (x *EnterSceneS2C) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *EnterSceneS2C) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *EnterSceneS2C) GetPos() *Pos {
	if x != nil {
		return x.Pos
	}
	return nil
}

//移动
type MovePosC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos *Pos `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *MovePosC2S) Reset() {
	*x = MovePosC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovePosC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePosC2S) ProtoMessage() {}

func (x *MovePosC2S) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePosC2S.ProtoReflect.Descriptor instead.
func (*MovePosC2S) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{2}
}

func (x *MovePosC2S) GetPos() *Pos {
	if x != nil {
		return x.Pos
	}
	return nil
}

type MovePosS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` //角色id
	MapId  uint32 `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`    //地图id
	Pos    *Pos   `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *MovePosS2C) Reset() {
	*x = MovePosS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovePosS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePosS2C) ProtoMessage() {}

func (x *MovePosS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePosS2C.ProtoReflect.Descriptor instead.
func (*MovePosS2C) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{3}
}

func (x *MovePosS2C) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *MovePosS2C) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MovePosS2C) GetPos() *Pos {
	if x != nil {
		return x.Pos
	}
	return nil
}

//角色视野列表
type RoleViewListS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       uint32       `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`                              //1:完整列表 2:新增列表
	SceneId    uint32       `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`         //地图id
	MapId      uint32       `protobuf:"varint,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`               //地图id
	SceneRoles []*SceneRole `protobuf:"bytes,4,rep,name=scene_roles,json=sceneRoles,proto3" json:"scene_roles,omitempty"` //
}

func (x *RoleViewListS2C) Reset() {
	*x = RoleViewListS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleViewListS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleViewListS2C) ProtoMessage() {}

func (x *RoleViewListS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleViewListS2C.ProtoReflect.Descriptor instead.
func (*RoleViewListS2C) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{4}
}

func (x *RoleViewListS2C) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *RoleViewListS2C) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *RoleViewListS2C) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *RoleViewListS2C) GetSceneRoles() []*SceneRole {
	if x != nil {
		return x.SceneRoles
	}
	return nil
}

//角色视野删除
type RoleViewDelS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` //
}

func (x *RoleViewDelS2C) Reset() {
	*x = RoleViewDelS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleViewDelS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleViewDelS2C) ProtoMessage() {}

func (x *RoleViewDelS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleViewDelS2C.ProtoReflect.Descriptor instead.
func (*RoleViewDelS2C) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{5}
}

func (x *RoleViewDelS2C) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

var File_proto_scene_proto protoreflect.FileDescriptor

var file_proto_scene_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48,
	0x0a, 0x0d, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x43, 0x32, 0x53, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49,
	0x64, 0x3a, 0x05, 0x88, 0xb5, 0x18, 0xd0, 0x0f, 0x22, 0x9c, 0x01, 0x0a, 0x0d, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x53, 0x32, 0x43, 0x12, 0x33, 0x0a, 0x0d, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x63,
	0x65, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x6f, 0x73, 0x52, 0x03, 0x70, 0x6f, 0x73,
	0x3a, 0x05, 0x88, 0xb5, 0x18, 0xd0, 0x0f, 0x22, 0x32, 0x0a, 0x0a, 0x4d, 0x6f, 0x76, 0x65, 0x50,
	0x6f, 0x73, 0x43, 0x32, 0x53, 0x12, 0x1d, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x6f, 0x73, 0x52,
	0x03, 0x70, 0x6f, 0x73, 0x3a, 0x05, 0x88, 0xb5, 0x18, 0xd1, 0x0f, 0x22, 0x62, 0x0a, 0x0a, 0x4d,
	0x6f, 0x76, 0x65, 0x50, 0x6f, 0x73, 0x53, 0x32, 0x43, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65,
	0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x03, 0x70, 0x6f, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x6f, 0x73, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x3a, 0x05, 0x88, 0xb5, 0x18, 0xd1, 0x0f, 0x22,
	0x93, 0x01, 0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x65, 0x56, 0x69, 0x65, 0x77, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x32, 0x43, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65,
	0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x0b, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x72, 0x6f,
	0x6c, 0x65, 0x52, 0x0a, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x3a, 0x05,
	0x88, 0xb5, 0x18, 0xd2, 0x0f, 0x22, 0x30, 0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x56, 0x69, 0x65,
	0x77, 0x44, 0x65, 0x6c, 0x53, 0x32, 0x43, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64,
	0x3a, 0x05, 0x88, 0xb5, 0x18, 0xd3, 0x0f, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x50, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_scene_proto_rawDescOnce sync.Once
	file_proto_scene_proto_rawDescData = file_proto_scene_proto_rawDesc
)

func file_proto_scene_proto_rawDescGZIP() []byte {
	file_proto_scene_proto_rawDescOnce.Do(func() {
		file_proto_scene_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_scene_proto_rawDescData)
	})
	return file_proto_scene_proto_rawDescData
}

var file_proto_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_scene_proto_goTypes = []interface{}{
	(*EnterSceneC2S)(nil),   // 0: scene.EnterSceneC2S
	(*EnterSceneS2C)(nil),   // 1: scene.EnterSceneS2C
	(*MovePosC2S)(nil),      // 2: scene.MovePosC2S
	(*MovePosS2C)(nil),      // 3: scene.MovePosS2C
	(*RoleViewListS2C)(nil), // 4: scene.RoleViewListS2C
	(*RoleViewDelS2C)(nil),  // 5: scene.RoleViewDelS2C
	(*Notice)(nil),          // 6: common.notice
	(*Pos)(nil),             // 7: common.pos
	(*SceneRole)(nil),       // 8: common.scene_role
}
var file_proto_scene_proto_depIdxs = []int32{
	6, // 0: scene.EnterSceneS2C.common_notice:type_name -> common.notice
	7, // 1: scene.EnterSceneS2C.pos:type_name -> common.pos
	7, // 2: scene.MovePosC2S.pos:type_name -> common.pos
	7, // 3: scene.MovePosS2C.pos:type_name -> common.pos
	8, // 4: scene.RoleViewListS2C.scene_roles:type_name -> common.scene_role
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_scene_proto_init() }
func file_proto_scene_proto_init() {
	if File_proto_scene_proto != nil {
		return
	}
	file_proto_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_scene_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterSceneC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterSceneS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovePosC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovePosS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleViewListS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleViewDelS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_scene_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_scene_proto_goTypes,
		DependencyIndexes: file_proto_scene_proto_depIdxs,
		MessageInfos:      file_proto_scene_proto_msgTypes,
	}.Build()
	File_proto_scene_proto = out.File
	file_proto_scene_proto_rawDesc = nil
	file_proto_scene_proto_goTypes = nil
	file_proto_scene_proto_depIdxs = nil
}
