// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/scene.proto

// 包名

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//客户登录时获取当前场景信息
type LoginEnterC2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginEnterC2S) Reset() {
	*x = LoginEnterC2S{}
	mi := &file_proto_scene_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginEnterC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginEnterC2S) ProtoMessage() {}

func (x *LoginEnterC2S) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginEnterC2S.ProtoReflect.Descriptor instead.
func (*LoginEnterC2S) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{0}
}

type LoginEnterS2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommonNotice  *Notice                `protobuf:"bytes,1,opt,name=common_notice,json=commonNotice,proto3" json:"common_notice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginEnterS2C) Reset() {
	*x = LoginEnterS2C{}
	mi := &file_proto_scene_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginEnterS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginEnterS2C) ProtoMessage() {}

func (x *LoginEnterS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginEnterS2C.ProtoReflect.Descriptor instead.
func (*LoginEnterS2C) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{1}
}

func (x *LoginEnterS2C) GetCommonNotice() *Notice {
	if x != nil {
		return x.CommonNotice
	}
	return nil
}

//进入场景 优先scene_id，如果scene_id为0 转大场景map_id
type EnterSceneC2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SceneId       uint32                 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"` //场景id
	MapId         uint32                 `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`       //地图id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterSceneC2S) Reset() {
	*x = EnterSceneC2S{}
	mi := &file_proto_scene_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterSceneC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSceneC2S) ProtoMessage() {}

func (x *EnterSceneC2S) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSceneC2S.ProtoReflect.Descriptor instead.
func (*EnterSceneC2S) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{2}
}

func (x *EnterSceneC2S) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *EnterSceneC2S) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

type EnterSceneS2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommonNotice  *Notice                `protobuf:"bytes,1,opt,name=common_notice,json=commonNotice,proto3" json:"common_notice,omitempty"`
	SceneId       uint32                 `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"` //场景id
	MapId         uint32                 `protobuf:"varint,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`       //地图id
	Pos           *Pos                   `protobuf:"bytes,4,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterSceneS2C) Reset() {
	*x = EnterSceneS2C{}
	mi := &file_proto_scene_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterSceneS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSceneS2C) ProtoMessage() {}

func (x *EnterSceneS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSceneS2C.ProtoReflect.Descriptor instead.
func (*EnterSceneS2C) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{3}
}

func (x *EnterSceneS2C) GetCommonNotice() *Notice {
	if x != nil {
		return x.CommonNotice
	}
	return nil
}

func (x *EnterSceneS2C) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *EnterSceneS2C) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *EnterSceneS2C) GetPos() *Pos {
	if x != nil {
		return x.Pos
	}
	return nil
}

//移动
type MovePosC2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *Pos                   `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePosC2S) Reset() {
	*x = MovePosC2S{}
	mi := &file_proto_scene_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePosC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePosC2S) ProtoMessage() {}

func (x *MovePosC2S) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePosC2S.ProtoReflect.Descriptor instead.
func (*MovePosC2S) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{4}
}

func (x *MovePosC2S) GetPos() *Pos {
	if x != nil {
		return x.Pos
	}
	return nil
}

type MovePosS2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        uint64                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` //角色id
	MapId         uint32                 `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`    //地图id
	Pos           *Pos                   `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePosS2C) Reset() {
	*x = MovePosS2C{}
	mi := &file_proto_scene_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePosS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePosS2C) ProtoMessage() {}

func (x *MovePosS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePosS2C.ProtoReflect.Descriptor instead.
func (*MovePosS2C) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{5}
}

func (x *MovePosS2C) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *MovePosS2C) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MovePosS2C) GetPos() *Pos {
	if x != nil {
		return x.Pos
	}
	return nil
}

//角色视野列表
type RoleViewListS2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`                              //1:完整列表 2:新增列表
	SceneId       uint32                 `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`         //地图id
	MapId         uint32                 `protobuf:"varint,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`               //地图id
	SceneRoles    []*SceneRole           `protobuf:"bytes,4,rep,name=scene_roles,json=sceneRoles,proto3" json:"scene_roles,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleViewListS2C) Reset() {
	*x = RoleViewListS2C{}
	mi := &file_proto_scene_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleViewListS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleViewListS2C) ProtoMessage() {}

func (x *RoleViewListS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleViewListS2C.ProtoReflect.Descriptor instead.
func (*RoleViewListS2C) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{6}
}

func (x *RoleViewListS2C) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *RoleViewListS2C) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *RoleViewListS2C) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *RoleViewListS2C) GetSceneRoles() []*SceneRole {
	if x != nil {
		return x.SceneRoles
	}
	return nil
}

//角色视野删除
type RoleViewDelS2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        uint64                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleViewDelS2C) Reset() {
	*x = RoleViewDelS2C{}
	mi := &file_proto_scene_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleViewDelS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleViewDelS2C) ProtoMessage() {}

func (x *RoleViewDelS2C) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleViewDelS2C.ProtoReflect.Descriptor instead.
func (*RoleViewDelS2C) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{7}
}

func (x *RoleViewDelS2C) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

var File_proto_scene_proto protoreflect.FileDescriptor

const file_proto_scene_proto_rawDesc = "" +
	"\n" +
	"\x11proto/scene.proto\x12\x05scene\x1a\x12proto/common.proto\"\x16\n" +
	"\rLoginEnterC2S:\x05\x88\xb5\x18\xd0\x0f\"K\n" +
	"\rLoginEnterS2C\x123\n" +
	"\rcommon_notice\x18\x01 \x01(\v2\x0e.common.noticeR\fcommonNotice:\x05\x88\xb5\x18\xd0\x0f\"H\n" +
	"\rEnterSceneC2S\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\rR\asceneId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\rR\x05mapId:\x05\x88\xb5\x18\xd1\x0f\"\x9c\x01\n" +
	"\rEnterSceneS2C\x123\n" +
	"\rcommon_notice\x18\x01 \x01(\v2\x0e.common.noticeR\fcommonNotice\x12\x19\n" +
	"\bscene_id\x18\x02 \x01(\rR\asceneId\x12\x15\n" +
	"\x06map_id\x18\x03 \x01(\rR\x05mapId\x12\x1d\n" +
	"\x03pos\x18\x04 \x01(\v2\v.common.posR\x03pos:\x05\x88\xb5\x18\xd1\x0f\"2\n" +
	"\n" +
	"MovePosC2S\x12\x1d\n" +
	"\x03pos\x18\x03 \x01(\v2\v.common.posR\x03pos:\x05\x88\xb5\x18\xd2\x0f\"b\n" +
	"\n" +
	"MovePosS2C\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x04R\x06roleId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\rR\x05mapId\x12\x1d\n" +
	"\x03pos\x18\x03 \x01(\v2\v.common.posR\x03pos:\x05\x88\xb5\x18\xd2\x0f\"\x93\x01\n" +
	"\x0fRoleViewListS2C\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x19\n" +
	"\bscene_id\x18\x02 \x01(\rR\asceneId\x12\x15\n" +
	"\x06map_id\x18\x03 \x01(\rR\x05mapId\x123\n" +
	"\vscene_roles\x18\x04 \x03(\v2\x12.common.scene_roleR\n" +
	"sceneRoles:\x05\x88\xb5\x18\xd3\x0f\"0\n" +
	"\x0eRoleViewDelS2C\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x04R\x06roleId:\x05\x88\xb5\x18\xd4\x0fB\rZ\vproto/pb;pbP\x00b\x06proto3"

var (
	file_proto_scene_proto_rawDescOnce sync.Once
	file_proto_scene_proto_rawDescData []byte
)

func file_proto_scene_proto_rawDescGZIP() []byte {
	file_proto_scene_proto_rawDescOnce.Do(func() {
		file_proto_scene_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scene_proto_rawDesc), len(file_proto_scene_proto_rawDesc)))
	})
	return file_proto_scene_proto_rawDescData
}

var file_proto_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_scene_proto_goTypes = []any{
	(*LoginEnterC2S)(nil),   // 0: scene.LoginEnterC2S
	(*LoginEnterS2C)(nil),   // 1: scene.LoginEnterS2C
	(*EnterSceneC2S)(nil),   // 2: scene.EnterSceneC2S
	(*EnterSceneS2C)(nil),   // 3: scene.EnterSceneS2C
	(*MovePosC2S)(nil),      // 4: scene.MovePosC2S
	(*MovePosS2C)(nil),      // 5: scene.MovePosS2C
	(*RoleViewListS2C)(nil), // 6: scene.RoleViewListS2C
	(*RoleViewDelS2C)(nil),  // 7: scene.RoleViewDelS2C
	(*Notice)(nil),          // 8: common.notice
	(*Pos)(nil),             // 9: common.pos
	(*SceneRole)(nil),       // 10: common.scene_role
}
var file_proto_scene_proto_depIdxs = []int32{
	8,  // 0: scene.LoginEnterS2C.common_notice:type_name -> common.notice
	8,  // 1: scene.EnterSceneS2C.common_notice:type_name -> common.notice
	9,  // 2: scene.EnterSceneS2C.pos:type_name -> common.pos
	9,  // 3: scene.MovePosC2S.pos:type_name -> common.pos
	9,  // 4: scene.MovePosS2C.pos:type_name -> common.pos
	10, // 5: scene.RoleViewListS2C.scene_roles:type_name -> common.scene_role
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_scene_proto_init() }
func file_proto_scene_proto_init() {
	if File_proto_scene_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scene_proto_rawDesc), len(file_proto_scene_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_scene_proto_goTypes,
		DependencyIndexes: file_proto_scene_proto_depIdxs,
		MessageInfos:      file_proto_scene_proto_msgTypes,
	}.Build()
	File_proto_scene_proto = out.File
	file_proto_scene_proto_goTypes = nil
	file_proto_scene_proto_depIdxs = nil
}
